import type { AuditResult } from "./types";

/** Sample report for first-time visitors — illustrative data only. */
export const DEMO_AUDIT_RESULT: AuditResult = {
  url: "https://demo-store.example.com",
  auditedAt: new Date().toISOString(),
  includePaidMedia: true,
  aiGenerated: false,
  scores: {
    overall: 72,
    ruleBased: 68,
    lighthouseSeo: 81,
  },
  summary: {
    totalPages: 12,
    totalIssues: 18,
    issuesBySeverity: { critical: 1, high: 4, medium: 8, low: 5 },
    avgLighthousePerformance: 64,
    avgLighthouseSeo: 81,
  },
  site: {
    robotsTxt: { found: true, sitemapUrls: ["https://demo-store.example.com/sitemap.xml"], disallowRules: [] },
    sitemap: { found: true, urlCount: 48 },
    httpsUsed: true,
    mixedContentWarnings: 0,
    urlConsistencyIssues: [],
  },
  lighthouse: [
    { url: "https://demo-store.example.com", performance: 58, accessibility: 88, bestPractices: 92, seo: 85, lcp: 3200, cls: 0.08 },
  ],
  pages: [],
  issues: [
    {
      id: "demo-1",
      severity: "critical",
      category: "metadata",
      title: "Missing meta descriptions on key pages",
      description: "5 product pages have no meta description, which hurts click-through from search.",
      recommendation: "Write unique 120–160 character descriptions for each page.",
    },
    {
      id: "demo-2",
      severity: "high",
      category: "performance",
      title: "Slow Largest Contentful Paint on homepage",
      description: "LCP is 3.2s — above the 2.5s target for good user experience.",
      pageUrl: "https://demo-store.example.com",
      recommendation: "Compress the hero image and preload critical assets.",
    },
    {
      id: "demo-3",
      severity: "high",
      category: "content",
      title: "Duplicate title tags",
      description: "3 pages share the same title, confusing search engines about which to rank.",
      recommendation: "Give every page a unique, descriptive title.",
    },
  ],
  recommendations: [
    {
      id: "demo-rec-1",
      severity: "high",
      title: "Add unique meta descriptions to product pages",
      description: "If this were my site, I'd start here — meta descriptions directly influence click-through rate from Google.",
      fixInstructions: "Audit each product URL and add a compelling 120–160 character summary with the primary keyword.",
      impact: "quick-win",
      estimatedSeoImpact: "High — can improve organic CTR by 5–15%",
      affectedPages: ["https://demo-store.example.com/products"],
    },
    {
      id: "demo-rec-2",
      severity: "high",
      title: "Compress homepage hero image",
      description: "Your hero image is likely the main reason LCP is slow — fixing it improves both SEO and conversions.",
      fixInstructions: "Convert PNG/JPEG heroes to WebP or AVIF and serve responsive sizes via srcset.",
      impact: "quick-win",
      estimatedSeoImpact: "High — faster LCP supports rankings and paid landing page quality scores",
    },
    {
      id: "demo-rec-3",
      severity: "medium",
      title: "Build a branded search campaign",
      description: "Capture high-intent shoppers searching for your brand while organic rankings mature.",
      fixInstructions: "Launch exact-match Google Search ads on your brand name with sitelink extensions.",
      impact: "long-term",
      estimatedSeoImpact: "Medium — protects brand traffic and supports revenue",
    },
  ],
  paidStrategy: {
    included: true,
    summary: "Sample strategy: prioritize Google Search for product-intent keywords, then retarget site visitors on Meta.",
    businessTypeGuess: "E-commerce / online retail",
    keywords: [
      {
        id: "demo-kw-1",
        keyword: "organic skincare products",
        intent: "commercial",
        matchType: "phrase",
        rationale: "Matches core product category from page titles.",
        suggestedLandingPage: "https://demo-store.example.com/products",
        priority: "high",
      },
    ],
    channels: [
      {
        id: "demo-ch-1",
        channel: "google-search",
        channelLabel: "Google Search Ads",
        priority: "primary",
        rationale: "Capture shoppers actively searching for your products.",
        estimatedBudgetRange: "$500–$2,000/month",
        bestFor: "Demand capture",
        tactics: ["Phrase match on top 5 keywords", "Weekly negative keyword review"],
      },
    ],
    quickWins: ["Install conversion tracking before spending", "Launch brand search campaign"],
    budgetGuidance: "Start with $1,000/month: 60% search, 25% retargeting, 15% testing.",
    launchTimeline: [
      {
        id: "demo-phase-1",
        phase: "Foundation",
        timeframe: "Week 1–2",
        goals: ["Tracking ready"],
        tasks: ["Install Google Tag Manager", "Set up conversion events"],
      },
      {
        id: "demo-phase-2",
        phase: "Search launch",
        timeframe: "Week 3–4",
        goals: ["Capture demand"],
        tasks: ["Launch Search campaigns on top keywords"],
      },
    ],
    aiGenerated: false,
  },
};
